// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-1.0
// DO NOT EDIT

#[allow(unused_imports)]
use crate::auto::*;

#[doc(alias = "WpObjectFeatures")]
pub type ObjectFeatures = u32;
