[package]
name = "cobble-bar-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
futures = "0.3.30"
glib = "0.19.6"
libc = "0.2.154"
wireplumber-sys = { path = "../wireplumber-sys" }
